using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using RunningUp.Progression.MonthlyApex;
using Xunit;

namespace RunningUp.Domain.Tests
{
    /// <summary>
    /// Cross-implementation conformance for the Monthly Apex ladder.
    ///
    /// The rule set is implemented three times on purpose: SQL is the authority, the JS
    /// engine drives tooling and simulation, and this C# layer gives the Unity client an
    /// offline preview. Three implementations is a real drift risk (R-06 / AUDIT_08 F-08-1),
    /// so rather than trusting that they agree, this suite replays a fixture generated by
    /// the JS engine and asserts the C# results match step by step.
    ///
    /// If the client ever disagrees with the engine about what a run is worth, this fails.
    /// Regenerate the fixture with: node tools/conformance/export-fixtures.mjs
    /// </summary>
    public class MonthlyApexConformanceTests
    {
        private static readonly JsonElement Fixture = LoadFixture();

        private static JsonElement LoadFixture()
        {
            var directory = new DirectoryInfo(AppContext.BaseDirectory);
            while (directory != null && !File.Exists(Path.Combine(directory.FullName, "package.json")))
            {
                directory = directory.Parent;
            }

            Assert.True(directory != null, "could not locate the repository root from the test output directory");

            var path = Path.Combine(directory.FullName, "content", "conformance", "monthly-apex-cases.json");
            Assert.True(File.Exists(path), $"conformance fixture missing at {path}");

            return JsonDocument.Parse(File.ReadAllText(path)).RootElement.Clone();
        }

        [Fact]
        public void DirectionLockConstantsMatchTheFixture()
        {
            var lockSection = Fixture.GetProperty("direction_lock");

            // Read into a local first: xUnit's analyzer rejects a const in the `actual`
            // position, and inverting the arguments would misrepresent which side is the
            // reference value. The fixture is the reference; the client must match it.
            var fixtureFinalApexMeters = lockSection.GetProperty("final_apex_meters").GetInt32();
            var clientFinalApexMeters = MonthlyApexLadder.FinalApexMeters;
            Assert.Equal(fixtureFinalApexMeters, clientFinalApexMeters);
            Assert.Equal(lockSection.GetProperty("checkpoint_count").GetInt32(), MonthlyApexLadder.CheckpointMeters.Count);
            Assert.Equal(lockSection.GetProperty("final_rank_id").GetString(), MonthlyApexLadder.Ranks.Last().Id);
        }

        [Fact]
        public void CheckpointSeedIsIdenticalToTheEngine()
        {
            var expected = Fixture.GetProperty("checkpoint_meters")
                .EnumerateArray().Select(e => e.GetInt32()).ToList();

            Assert.Equal(expected, MonthlyApexLadder.CheckpointMeters.ToList());
            Assert.Equal(52, expected.Count);
            Assert.Equal(1_000_000, expected.Last());
            Assert.DoesNotContain(expected, m => m > 1_000_000);
        }

        [Fact]
        public void RankTableIsIdenticalToTheEngine()
        {
            var expected = Fixture.GetProperty("ranks").EnumerateArray().ToList();
            Assert.Equal(expected.Count, MonthlyApexLadder.Ranks.Count);

            for (var i = 0; i < expected.Count; i++)
            {
                var wanted = expected[i];
                var actual = MonthlyApexLadder.Ranks[i];

                Assert.Equal(wanted.GetProperty("id").GetString(), actual.Id);
                Assert.Equal(wanted.GetProperty("min_meters").GetInt32(), actual.MinMeters);

                var max = wanted.GetProperty("max_meters");
                if (max.ValueKind == JsonValueKind.Null)
                {
                    Assert.Null(actual.MaxMeters);
                }
                else
                {
                    Assert.Equal(max.GetInt32(), actual.MaxMeters);
                }
            }

            // DL-1: nothing sorts above the crown.
            Assert.Equal("world_crown", MonthlyApexLadder.Ranks.Last().Id);
            Assert.Null(MonthlyApexLadder.Ranks.Last().MaxMeters);
        }

        [Fact]
        public void EveryRankBoundaryProbeAgrees()
        {
            foreach (var probe in Fixture.GetProperty("rank_boundary_probes").EnumerateArray())
            {
                var meters = probe.GetProperty("meters").GetInt32();
                var expected = probe.GetProperty("rank").GetString();
                Assert.Equal(expected, MonthlyApexLadder.RankForMeters(meters).Id);
            }
        }

        public static IEnumerable<object[]> Cases()
        {
            foreach (var testCase in Fixture.GetProperty("cases").EnumerateArray())
            {
                yield return new object[] { testCase.GetProperty("id").GetString() };
            }
        }

        [Theory]
        [MemberData(nameof(Cases))]
        public void CaseReplayMatchesTheEngineStepByStep(string caseId)
        {
            var testCase = Fixture.GetProperty("cases")
                .EnumerateArray()
                .Single(c => c.GetProperty("id").GetString() == caseId);

            var progress = ApexProgress.Empty;
            var stepIndex = 0;

            foreach (var step in testCase.GetProperty("steps").EnumerateArray())
            {
                var sessionMeters = step.GetProperty("session_meters").GetInt32();
                var result = MonthlyApexLadder.Apply(progress, sessionMeters);
                progress = result.After;

                var expectedCrossed = step.GetProperty("crossed_checkpoint_ids")
                    .EnumerateArray().Select(e => e.GetString()).ToList();

                Assert.Equal(expectedCrossed, result.CrossedCheckpointIds.ToList());
                Assert.Equal(step.GetProperty("crossed_count").GetInt32(), result.CrossedCheckpointIds.Count);
                Assert.Equal(step.GetProperty("rank_after").GetString(), result.RankAfter);
                Assert.Equal(step.GetProperty("world_crown_awarded_now").GetBoolean(), result.WorldCrownAwardedNow);
                Assert.Equal(step.GetProperty("apex_axis_unlocked_now").GetBoolean(), result.ApexAxisUnlockedNow);
                Assert.Equal(step.GetProperty("laddered_meters_after").GetInt32(), result.After.LadderedMeters);
                Assert.Equal(step.GetProperty("over_crown_meters_after").GetInt32(), result.After.OverCrownMeters);
                Assert.Equal(step.GetProperty("base_run_reward_applies").GetBoolean(), result.BaseRunRewardApplies);

                stepIndex++;
            }

            var final = testCase.GetProperty("final");
            Assert.Equal(final.GetProperty("laddered_meters").GetInt32(), progress.LadderedMeters);
            Assert.Equal(final.GetProperty("over_crown_meters").GetInt32(), progress.OverCrownMeters);
            Assert.Equal(final.GetProperty("rank").GetString(), MonthlyApexLadder.RankForMeters(progress.LadderedMeters).Id);
            Assert.Equal(final.GetProperty("world_crown_awarded").GetBoolean(), progress.WorldCrownAwarded);
            Assert.Equal(final.GetProperty("apex_axis_unlocked").GetBoolean(), progress.ApexAxisUnlocked);
        }

        // ------------------------------------------------------------------
        // Direction lock DL-1, asserted independently of the fixture
        // ------------------------------------------------------------------

        [Fact]
        public void LadderNeverExceedsTheCrownHoweverFarTheUserRuns()
        {
            var progress = ApexProgress.Empty;
            for (var i = 0; i < 60; i++)
            {
                progress = MonthlyApexLadder.Apply(progress, 50_000).After;
            }

            Assert.Equal(1_000_000, progress.LadderedMeters);
            Assert.Equal(2_000_000, progress.OverCrownMeters);
            Assert.Equal("world_crown", MonthlyApexLadder.RankForMeters(progress.LadderedMeters).Id);
        }

        [Fact]
        public void RunningPastTheCrownStillEarnsButUnlocksNothingNew()
        {
            var crowned = MonthlyApexLadder.Apply(ApexProgress.Empty, 1_000_000).After;
            var further = MonthlyApexLadder.Apply(crowned, 25_000);

            Assert.Empty(further.CrossedCheckpointIds);
            Assert.False(further.WorldCrownAwardedNow);
            Assert.False(further.ApexAxisUnlockedNow);
            Assert.Equal("world_crown", further.RankAfter);
            Assert.Equal(25_000, further.OverCrownMetersAdded);
            Assert.True(further.BaseRunRewardApplies);
        }

        [Fact]
        public void SnapshotNeverAdvertisesATierAboveTheFinalOne()
        {
            var crowned = MonthlyApexLadder.Apply(ApexProgress.Empty, 1_050_000).After;
            var snapshot = MonthlyApexLadder.Snapshot(crowned);

            Assert.False(snapshot.HasTierAboveFinal);
            Assert.True(snapshot.IsFinalRank);
            Assert.Empty(snapshot.Next);
            Assert.Equal(52, snapshot.CheckpointsReached);
            Assert.Equal(52, snapshot.CheckpointsTotal);
        }

        [Fact]
        public void EveryCheckpointIsClaimedExactlyOnceAcrossAFullMonth()
        {
            var progress = ApexProgress.Empty;
            var claimed = new List<string>();

            for (var i = 0; i < 200; i++)
            {
                var result = MonthlyApexLadder.Apply(progress, 5_000);
                progress = result.After;
                claimed.AddRange(result.CrossedCheckpointIds);
            }

            Assert.Equal(1_000_000, progress.LadderedMeters);
            Assert.Equal(52, claimed.Count);
            Assert.Equal(52, claimed.Distinct().Count());
            Assert.True(progress.WorldCrownAwarded);
            Assert.True(progress.ApexAxisUnlocked);
        }

        [Fact]
        public void CheckpointIdsMatchTheServerNamingIncludingTheFractionalOne()
        {
            Assert.Equal("apex_cp_01_0km", MonthlyApexLadder.CheckpointId(0));
            Assert.Equal("apex_cp_11_42p195km", MonthlyApexLadder.CheckpointId(10));
            Assert.Equal("apex_cp_52_1000km", MonthlyApexLadder.CheckpointId(51));
        }

        [Fact]
        public void NegativeDistanceIsRejected()
        {
            Assert.Throws<ArgumentOutOfRangeException>(() => MonthlyApexLadder.Apply(ApexProgress.Empty, -1));
            Assert.Throws<ArgumentOutOfRangeException>(() => MonthlyApexLadder.RankForMeters(-1));
        }
    }
}
